### PR TITLE
Add more options to dask array

### PR DESCRIPTION
**Pull request by boazmohar**
1. add the option to force a dtype as the coarsen function outputs floats
2. added compute and return_stored to enable lazy execution

I see 2 error but they are unrealted to my changes.
Test would follow if @constantinpape you approve of these additions.

Boaz

### CODE REVIEW

**Comment by constantinpape** [comment]
Hi Boaz,
yes I think the changes look good. Please go ahead with the tests :).

**Comment by boazmohar** [comment]
thanks @constantinpape , here are the tests, le me know what you think.

Boaz

**Comment by constantinpape** [comment]
The changes look good @boazmohar. But two tests are now failing:
- test_make_bdv.TestMakeBdvDaskN5
- test_make_bdv.TestMakeBdvDaskZarr

They worked on master before this PR. I am not sure if this is related to the changes here, or if it is due to some version update, e.g. dask. Do you have any idea?

**Comment by boazmohar** [comment]
Took a while but I found the issue, it was a tuple unpacking i missed.

**Comment by constantinpape** [comment]
Awesome, thank you @boazmohar!

**Pull request merged**
